// This source code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// © sbtnc
// 2019-5-19

//@version=3
study(title="Chaikin Oscillator", shorttitle="Chaikin Osc")

//------------------------------ Inputs ------------------------------

fast = input(3, minval=1, title="Fast Length")
slow = input(10, minval=1, title="Slow Length")

//------------------------------ Colors ------------------------------

color_negative = #ff4e3e
color_positive = #3fbe53
color_neutral = #656565

//------------------------------- Logic ------------------------------

// orignal logic
osc = ema(accdist, fast) - ema(accdist, slow)

positive = osc > 0

//------------------------- Plotting & styling ------------------------

transp_area = 92
transp_osc = 20
transp_zero = 100

color = positive ? color_positive : color_negative

zero = plot(0, color=color_neutral, transp=transp_zero, title="zero")
chaikinOsc = plot(osc, color=color_neutral, transp=transp_osc, title="Chaikin Oscillator")

fill(zero, chaikinOsc, color=color, transp=transp_area, title="area")
