// © sbtnc
// Created: 2024-03-10
// Last modified: 2024-03-10
// Version 1.0

// @version=5

indicator("Multi-Timeframe Separators", "MTF Separators", overlay = true, max_lines_count = 500)



//--------------------------------------------------------------------
//#region                      Constants
//--------------------------------------------------------------------

color   COLOR_1 = color.green
color   COLOR_2 = color.orange
color   COLOR_3 = color.red
color   COLOR_4 = color.blue

//#endregion


//--------------------------------------------------------------------
//#region                        Inputs
//--------------------------------------------------------------------

g1 = "Separators"

enableSeparatorInput1       = input.bool        (true,      "",             group = g1, inline = "#1")
separatorTimeframeInput1    = input.timeframe   ("D",       "",             group = g1, inline = "#1")
separatorLookbackInput1     = input.int         (500,       "",             group = g1, inline = "#1", minval = 1, maxval = 500, display = display.none)
enableSeparatorInput2       = input.bool        (true,      "",             group = g1, inline = "#2")
separatorTimeframeInput2    = input.timeframe   ("W",       "",             group = g1, inline = "#2")
separatorLookbackInput2     = input.int         (500,       "",             group = g1, inline = "#2", minval = 1, maxval = 500, display = display.none)
enableSeparatorInput3       = input.bool        (true,      "",             group = g1, inline = "#3")
separatorTimeframeInput3    = input.timeframe   ("M",       "",             group = g1, inline = "#3")
separatorLookbackInput3     = input.int         (500,       "",             group = g1, inline = "#3", minval = 1, maxval = 500, display = display.none)
enableSeparatorInput4       = input.bool        (false,     "",             group = g1, inline = "#4")
separatorTimeframeInput4    = input.timeframe   ("12M",     "",             group = g1, inline = "#4")
separatorLookbackInput4     = input.int         (500,       "",             group = g1, inline = "#4", minval = 1, maxval = 500, display = display.none)

g2 = "Style"

separatorColorInput1        = input.color       (COLOR_1,   "",             group = g2, inline = "#1")
separatorWidthInput1        = input.int         (1,         "",             group = g2, inline = "#1", minval = 1, display = display.none)
separatorStyleInput1        = input.string      ("Dotted",  "",             group = g2, inline = "#1", options =["Solid", "Dashed", "Dotted"], display = display.none)
separatorColorInput2        = input.color       (COLOR_2,   "",             group = g2, inline = "#2")
separatorWidthInput2        = input.int         (1,         "",             group = g2, inline = "#2", minval = 1, display = display.none)
separatorStyleInput2        = input.string      ("Solid",   "",             group = g2, inline = "#2", options =["Solid", "Dashed", "Dotted"], display = display.none)
separatorColorInput3        = input.color       (COLOR_3,   "",             group = g2, inline = "#3")
separatorWidthInput3        = input.int         (2,         "",             group = g2, inline = "#3", minval = 1, display = display.none)
separatorStyleInput3        = input.string      ("Solid",   "",             group = g2, inline = "#3", options =["Solid", "Dashed", "Dotted"], display = display.none)
separatorColorInput4        = input.color       (COLOR_4,   "",             group = g2, inline = "#4")
separatorWidthInput4        = input.int         (3,         "",             group = g2, inline = "#4", minval = 1, display = display.none)
separatorStyleInput4        = input.string      ("Solid",   "",             group = g2, inline = "#4", options =["Solid", "Dashed", "Dotted"], display = display.none)

g3 = "Preferences"

showNextSeparatorInput      = input.bool        (false,     "Show Next",    group = g3)

//#endregion


//--------------------------------------------------------------------
//#region                         Types 
//--------------------------------------------------------------------
//#endregion


//--------------------------------------------------------------------
//#region                   Functions & methods
//--------------------------------------------------------------------

// @funcion Get the line style from a given input setting
// @returns const string
getLineStyle(string input) =>
    var _style = switch input
        "Solid"     => line.style_solid
        "Dotted"    => line.style_dotted
        "Dashed"    => line.style_dashed


drawSeparator(bool isEnabled, string tf, color color, int width, string style, int lookback) =>
    var lineArray = array.new_line()
    _canDisplayOnChartTimeframe = timeframe.in_seconds(tf) > timeframe.in_seconds()

    if isEnabled and _canDisplayOnChartTimeframe and timeframe.change(tf)
        // y1 and y2 should not be equal prices otherwise draw vertical lines
        lineArray.push(
             line.new(time, open, time, open + syminfo.mintick, xloc.bar_time, extend.both, color, getLineStyle(style), width)
             )

        log.info(
             "\n high {0} low {0}",
             high, low)

        if lineArray.size() > lookback
            line.delete(lineArray.shift())

        // Projection
        if showNextSeparatorInput
            var line projectionLine = line.new(na, na, na, na, xloc.bar_time, extend.both, color, getLineStyle(style), width)

            nextTime = time + timeframe.in_seconds(tf) * 1000
            log.info("\n {0}", timeframe.in_seconds(tf))
            log.info(
                 "\n time {0}" +
                 "\n next time {1}",
                 str.format_time(time),
                 str.format_time(nextTime)
                 )
            projectionLine.set_xy1(nextTime, open)
            projectionLine.set_xy2(nextTime, syminfo.mintick)

//#endregion


//--------------------------------------------------------------------
//#region                 Variables declarations
//--------------------------------------------------------------------
//#endregion


//--------------------------------------------------------------------
//#region                         Logic
//--------------------------------------------------------------------
//#endregion


//--------------------------------------------------------------------
//#region                        Visuals
//--------------------------------------------------------------------

drawSeparator(enableSeparatorInput1, separatorTimeframeInput1, separatorColorInput1, separatorWidthInput1, separatorStyleInput1, separatorLookbackInput1)
drawSeparator(enableSeparatorInput2, separatorTimeframeInput2, separatorColorInput2, separatorWidthInput2, separatorStyleInput2, separatorLookbackInput2)
drawSeparator(enableSeparatorInput3, separatorTimeframeInput3, separatorColorInput3, separatorWidthInput3, separatorStyleInput3, separatorLookbackInput3)
drawSeparator(enableSeparatorInput4, separatorTimeframeInput4, separatorColorInput4, separatorWidthInput4, separatorStyleInput4, separatorLookbackInput4)

//#endregion


//--------------------------------------------------------------------
//#region                         Alerts
//--------------------------------------------------------------------
//#endregion


//--------------------------------------------------------------------
//#region                         Debug
//--------------------------------------------------------------------
//#endregion


//--------------------------------------------------------------------
//#region                      Performances
//--------------------------------------------------------------------
//#endregion