// This source code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// © sbtnc
// Created: 2019-01-05
// Last modified: 2025-12-05
// Version 3.0

// @version=6
indicator(title = "Multiple Moving Averages", shorttitle = "MAs", overlay = true)


//--------------------------------------------------------------------
//#region                      Constants
//--------------------------------------------------------------------

color   COLOR1          = color.new(#c9daf8, 0)
color   COLOR2          = color.new(#a4c2f4, 4)
color   COLOR3          = color.new(#6d9eeb, 8)
color   COLOR4          = color.new(#3c78d8, 12)
color   COLOR5          = color.new(#0b5394, 16)
int     PLOT_LINEWIDTH  = 1
string  LINE_EXTEND     = extend.none
string  LINE_STYLE      = line.style_dashed
int     LINE_WIDTH      = 1

//#endregion



//--------------------------------------------------------------------
//#region                         Types 
//--------------------------------------------------------------------

enum maType
    sma     = "SMA" 
    ema     = "EMA"
    smma    = "SMMA (RMA)"
    wma     = "WMA"
    vwma    = "VWMA"

//#endregion


//--------------------------------------------------------------------
//#region                        Inputs
//--------------------------------------------------------------------

// Groups.

string g1 = "#1"
string g2 = "#2"
string g3 = "#3"
string g4 = "#4"
string g5 = "#5"
string g6 = "Preferences"

// Tooltips.

string timeframeTooltip = "You can display a Moving Average from a higher timeframe. " +
                     "Note: It will be automatically hidden when switching the chart to a timeframe higher than its timeframe."

// Inputs.

bool    enableInput1            = input.bool        (defval = true,         title = "Display",                      group = g1)
maType  typeInput1              = input.enum        (defval = maType.ema,   title = "Type",                         group = g1, active = enableInput1)
int     lengthInput1            = input.int         (defval = 9,            title = "Length",                       group = g1, active = enableInput1, minval = 1)
float   sourceInput1            = input.source      (defval = close,        title = "Source",                       group = g1, active = enableInput1)
int     offsetInput1            = input.int         (defval = 0,            title = "Offset",                       group = g1, active = enableInput1)
string  timeframeInput1         = input.timeframe   (defval = "",           title = "Timeframe",                    group = g1, active = enableInput1, tooltip = timeframeTooltip)
color   colorInput1             = input.color       (defval = COLOR1,       title = "Color",                        group = g1, active = enableInput1)

bool    enableInput2            = input.bool        (defval = true,         title = "Display",                      group = g2)
maType  typeInput2              = input.enum        (defval = maType.ema,   title = "Type",                         group = g2, active = enableInput2)
int     lengthInput2            = input.int         (defval = 20,           title = "Length",                       group = g2, active = enableInput2, minval = 1)
float   sourceInput2            = input.source      (defval = close,        title = "Source",                       group = g2, active = enableInput2)
int     offsetInput2            = input.int         (defval = 0,            title = "Offset",                       group = g2, active = enableInput2)
string  timeframeInput2         = input.timeframe   (defval = "",           title = "Timeframe",                    group = g2, active = enableInput2, tooltip = timeframeTooltip)
color   colorInput2             = input.color       (defval = COLOR2,       title = "Color",                        group = g2, active = enableInput2)

bool    enableInput3            = input.bool        (defval = true,         title = "Display",                      group = g3)
maType  typeInput3              = input.enum        (defval = maType.ema,   title = "Type",                         group = g3, active = enableInput3)
int     lengthInput3            = input.int         (defval = 50,           title = "Length",                       group = g3, active = enableInput3, minval = 1)
float   sourceInput3            = input.source      (defval = close,        title = "Source",                       group = g3, active = enableInput3)
int     offsetInput3            = input.int         (defval = 0,            title = "Offset",                       group = g3, active = enableInput3)
string  timeframeInput3         = input.timeframe   (defval = "",           title = "Timeframe",                    group = g3, active = enableInput3, tooltip = timeframeTooltip)
color   colorInput3             = input.color       (defval = COLOR3,       title = "Color",                        group = g3, active = enableInput3)

bool    enableInput4            = input.bool        (defval = true,         title = "Display",                      group = g4)
maType  typeInput4              = input.enum        (defval = maType.ema,   title = "Type",                         group = g4, active = enableInput4)
int     lengthInput4            = input.int         (defval = 100,          title = "Length",                       group = g4, active = enableInput4, minval = 1)
float   sourceInput4            = input.source      (defval = close,        title = "Source",                       group = g4, active = enableInput4)
int     offsetInput4            = input.int         (defval = 0,            title = "Offset",                       group = g4, active = enableInput4)
string  timeframeInput4         = input.timeframe   (defval = "",           title = "Timeframe",                    group = g4, active = enableInput4, tooltip = timeframeTooltip)
color   colorInput4             = input.color       (defval = COLOR4,       title = "Color",                        group = g4, active = enableInput4)

bool    enableInput5            = input.bool        (defval = true,         title = "Display",                      group = g5)
maType  typeInput5              = input.enum        (defval = maType.ema,   title = "Type",                         group = g5, active = enableInput5)
int     lengthInput5            = input.int         (defval = 200,          title = "Length",                       group = g5, active = enableInput5, minval = 1)
float   sourceInput5            = input.source      (defval = close,        title = "Source",                       group = g5, active = enableInput5)
int     offsetInput5            = input.int         (defval = 0,            title = "Offset",                       group = g5, active = enableInput5)
string  timeframeInput5         = input.timeframe   (defval = "",           title = "Timeframe",                    group = g5, active = enableInput5, tooltip = timeframeTooltip)
color   colorInput5             = input.color       (defval = COLOR5,       title = "Color",                        group = g5, active = enableInput5)

bool    enableGapsInput         = input.bool        (defval = true,         title = "Wait for timeframe closes",    group = g6)
bool    showLevelsInput         = input.bool        (defval = true,         title = "Horizontal Levels",            group = g6) 
int     levelOffsetStartInput   = input.int         (defval = 0,            title = "Offset 1",                     group = g6, minval = 0)
int     levelOffsetEndInput     = input.int         (defval = 50,           title = "Offset 2",                     group = g6, minval = 1)

//#endregion


//--------------------------------------------------------------------
//#region                       Functions 
//--------------------------------------------------------------------

// @function Gets the selected Moving Average (MA).
// @returns  float
method get(simple maType this, series float source, simple int length) =>
    switch this
        maType.sma  => ta.sma (source, length)
        maType.ema  => ta.ema (source, length)
        maType.smma => ta.rma (source, length)
        maType.wma  => ta.wma (source, length)
        maType.vwma => ta.vwma(source, length)


// @function Checks if the specified timeframe is higher or equal than the chart context.
// @returns  bool
canDisplay(string tf) =>
    timeframe.in_seconds(tf) >= timeframe.in_seconds()


// @function Creates and updates the horizontal levels.
// @returns  void
draw(float y, color c) =>
    // Draws only when `y` is defined (e.g. when the MA's period exceed the number of bars).
    if not na(y)
        int _x1 = bar_index + levelOffsetStartInput
        int _x2 = _x1 + levelOffsetEndInput

        var _line = line.new(
             x1     = _x1,
             y1     = y, 
             x2     = _x2, 
             y2     = y, 
             xloc   = xloc.bar_index, 
             extend = LINE_EXTEND, 
             color  = c, 
             style  = LINE_STYLE, 
             width  = LINE_WIDTH
             )
        
        if barstate.islast
            line.set_xy1(_line, _x1, y)
            line.set_xy2(_line, _x2, y)

//#endregion


//--------------------------------------------------------------------
//#region                 Variables declarations
//--------------------------------------------------------------------

bool isVisible1 = enableInput1 and canDisplay(timeframeInput1)
bool isVisible2 = enableInput2 and canDisplay(timeframeInput2)
bool isVisible3 = enableInput3 and canDisplay(timeframeInput3)
bool isVisible4 = enableInput4 and canDisplay(timeframeInput4)
bool isVisible5 = enableInput5 and canDisplay(timeframeInput5)

//#endregion


//--------------------------------------------------------------------
//#region                         Logic
//--------------------------------------------------------------------

var gaps = enableGapsInput ? barmerge.gaps_on : barmerge.gaps_off

float ma1 = request.security(symbol = "", timeframe = timeframeInput1, expression = typeInput1.get(sourceInput1, lengthInput1), gaps = gaps)
float ma2 = request.security(symbol = "", timeframe = timeframeInput2, expression = typeInput2.get(sourceInput2, lengthInput2), gaps = gaps)
float ma3 = request.security(symbol = "", timeframe = timeframeInput3, expression = typeInput3.get(sourceInput3, lengthInput3), gaps = gaps)
float ma4 = request.security(symbol = "", timeframe = timeframeInput4, expression = typeInput4.get(sourceInput4, lengthInput4), gaps = gaps)
float ma5 = request.security(symbol = "", timeframe = timeframeInput5, expression = typeInput5.get(sourceInput5, lengthInput5), gaps = gaps)

//#endregion


//--------------------------------------------------------------------
//#region                   Plotting & styling
//--------------------------------------------------------------------

plot(series = isVisible1 ? ma1 : na, title = "Plot #1", color = colorInput1, linewidth = PLOT_LINEWIDTH, offset = offsetInput1, display = enableInput1 ? display.all : display.none)
plot(series = isVisible2 ? ma2 : na, title = "Plot #2", color = colorInput2, linewidth = PLOT_LINEWIDTH, offset = offsetInput2, display = enableInput2 ? display.all : display.none)
plot(series = isVisible3 ? ma3 : na, title = "Plot #3", color = colorInput3, linewidth = PLOT_LINEWIDTH, offset = offsetInput3, display = enableInput3 ? display.all : display.none)
plot(series = isVisible4 ? ma4 : na, title = "Plot #4", color = colorInput4, linewidth = PLOT_LINEWIDTH, offset = offsetInput4, display = enableInput4 ? display.all : display.none)
plot(series = isVisible5 ? ma5 : na, title = "Plot #5", color = colorInput5, linewidth = PLOT_LINEWIDTH, offset = offsetInput5, display = enableInput5 ? display.all : display.none)

if showLevelsInput
    if isVisible1
        draw(ma1, colorInput1)
    if isVisible2
        draw(ma2, colorInput2)
    if isVisible3    
        draw(ma3, colorInput3)
    if isVisible4
        draw(ma4, colorInput4)
    if isVisible5
        draw(ma5, colorInput5)

//#endregion