// This source code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// © sbtnc
// Created: 2019-01-05
// Last modified: 2023-05-05
// Version 2.0

// @version=5
indicator(title="Multiple Moving Averages", shorttitle="MAs", overlay=true)


//--------------------------------------------------------------------
//#region                        Inputs
//--------------------------------------------------------------------

i_source1 = input(close, "Source")
length_1 = input.int(9, minval=1, title="MA 1 length")
type_1 = input.string('EMA', options=['SMA', 'EMA', 'na'], title="MA 1 type")

i_source2 = input(close, "Source")
length_2 = input.int(20, minval=1, title="MA 2 length")
type_2 = input.string('EMA', options=['SMA', 'EMA', 'na'], title="MA 2 type")

i_source3 = input(close, "Source")
length_3 = input.int(50, minval=1, title="MA 3 length")
type_3 = input.string('EMA', options=['SMA', 'EMA', 'na'], title="MA 3 type")


i_source4 = input(close, "Source")
length_4 = input.int(100, minval=1, title="MA 4 length")
type_4 = input.string('EMA', options=['SMA', 'EMA', 'na'], title="MA 4 type")

i_source5 = input(close, "Source")
length_5 = input.int(200, minval=1, title="MA 5 length")
type_5 = input.string('EMA', options=['SMA', 'EMA', 'na'], title="MA 5 type")


offset = input.int(0, title="offset")

//#endregion


//--------------------------------------------------------------------
//#region                 Variables declarations
//--------------------------------------------------------------------

color_1 = color.new(#c9daf8, 0)
color_2 = color.new(#a4c2f4, 4)
color_3 = color.new(#6d9eeb, 8)
color_4 = color.new(#3c78d8, 12)
color_5 = color.new(#0b5394, 16)

//#endregion


//--------------------------------------------------------------------
//#region                         Logic
//--------------------------------------------------------------------

create(_type, _src, _length) =>
    _type == 'EMA' ? ta.ema(_src, _length) : _type == 'SMA' ? ta.sma(_src, _length) : na

ma1 = create(type_1, i_source1, length_1)
ma2 = create(type_2, i_source2, length_2)
ma3 = create(type_3, i_source3, length_3)
ma4 = create(type_4, i_source4, length_4)
ma5 = create(type_5, i_source5, length_5)

//#endregion


//--------------------------------------------------------------------
//#region                   Plotting & styling
//--------------------------------------------------------------------

line_width = 1

ma_1 = plot(ma1, color=color_1, linewidth=line_width, offset=offset, title="MA 1")
ma_2 = plot(ma2, color=color_2, linewidth=line_width, offset=offset, title="MA 2")
ma_3 = plot(ma3, color=color_3, linewidth=line_width, offset=offset, title="MA 3")
ma_4 = plot(ma4, color=color_4, linewidth=line_width, offset=offset, title="MA 4")
ma_5 = plot(ma5, color=color_5, linewidth=line_width, offset=offset, title="MA 5")

//#endregion