// This source code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// © sbtnc
// Created: 2025-04-16
// Last modified: 2025-04-16
// version 1.0

// @version=6
indicator("Intraday Opens", "Opens", overlay = true, max_lines_count = 500, dynamic_requests = true)


//--------------------------------------------------------------------
//#region                      Constants
//--------------------------------------------------------------------

color   COLOR_1         = color.green
string  LABEL_SIZE      = size.small
string  LABEL_STYLE     = label.style_none
string  LINE_STYLE      = line.style_solid
int     LINE_WIDTH      = 1
int     OFFSET_PADDING  = 4

//#endregion


//--------------------------------------------------------------------
//#region                         Types 
//--------------------------------------------------------------------

// @type Contains the open's data.
type Open 
    int     barIndex
    float   price 
    string  name
    color   color
    bool    display

//#endregion


//--------------------------------------------------------------------
//#region                        Inputs
//--------------------------------------------------------------------

string  group1              = "Opens"

bool    enableLevel1        = input.bool    (true,          title = "", inline = "Session #1", group = group1)
string  labelTextInput1     = input.string  ("New York",    title = "", inline = "Session #1", group = group1)
string  sessionInput1       = input.session ("0800-1200",   title = "", inline = "Session #1", group = group1)
color   openColorInput1     = input.color   (COLOR_1,       title = "", inline = "Session #1", group = group1)

string  group2              = "Styling" 
string  rightOffsetTooltip  = "Extend the current opens to the right of the last bar."

int     rightOffsetInput    = input.int     (20,            title = "Offset", group = group2, tooltip = rightOffsetTooltip, minval = 1, display = display.none)

//#endregion


//--------------------------------------------------------------------
//#region                   Functions & methods
//--------------------------------------------------------------------

// @function Calculate the right position of the open level.
// @returns  (int) The bar index. 
getRightBarIndex(int padding = 0) =>
    bar_index + rightOffsetInput + padding * OFFSET_PADDING


// @function Create and update the open level. An open is composed of a line and a label.
// @returns  void
draw(bool change, Open openData, int lookback, int padding) =>
    // @variable The reference of the last open line.
    var line _line = na

    // @variable The reference of the last open label.
    var label _label = label.new(
         x         = na,
         y         = na,
         text      = openData.name,
         style     = LABEL_STYLE,
         textcolor = openData.color,
         size      = LABEL_SIZE
         )

    // @variable The collection of historical open lines.
    var array<line> _lineArray  = array.new_line()


    // Update the old open and create the new open.

    if change
        int _x2 = getRightBarIndex()

        // Anchor the previous open end position.
        _line.set_x2(bar_index -1)//openData.barIndex -1)

        // Update the last open label position and tooltip.
        _label.set_xy(_x2, openData.price)
        _label.set_tooltip(str.tostring(openData.price, format.mintick))

        // Create and store the last open line.
        _line := line.new(
             x1    = bar_index, //openData.barIndex,
             x2    = _x2,
             y1    = openData.price,
             y2    = openData.price,
             color = openData.color,
             style = LINE_STYLE,
             width = LINE_WIDTH
             )
        array.push(_lineArray, _line)

        // Trim the exceeding number of drawings.
        if _lineArray.size() > lookback
            line.delete(_lineArray.shift())


    // Update the right position of the line.

    if barstate.islast
        int _x2 = getRightBarIndex(padding)
        _line.set_x2(_x2)
        _label.set_x(_x2)

//#endregion


//--------------------------------------------------------------------
//#region                 Variables declarations
//--------------------------------------------------------------------

// @variable The `Open` UDTs. 
var Open open1 = Open.new(name = labelTextInput1, color = openColorInput1, display = enableLevel1)

//#endregion


//--------------------------------------------------------------------
//#region                         Logic
//--------------------------------------------------------------------

// @function
// @returns 
getOpen(string session) =>
    int  _time      = time("D", session)
    bool _change    = ta.change(nz(_time)) > 0
    [_change, open]


bool start1 = if open1.display
    [startArray1, openArray1] = request.security_lower_tf("", "15", getOpen(sessionInput1))

    int changeIndex = startArray1.lastindexof(true)

    bool changed = changeIndex != -1

    open1.price := changed ? openArray1.get(changeIndex) : na
    
    changed

//#endregion


//--------------------------------------------------------------------
//#region                        Visuals
//--------------------------------------------------------------------

if open1.display
    draw(
         start1,
         open1,
         10,
         0//barstate.islast ? openArray.padding(4, proximityPaddingThreshold) : 0
         )

displayControls = display.status_line + display.price_scale + display.data_window

plot(
     series   = open1.price,
     title    = "#1",
     color    = open1.color,
     editable = false,
     display  = enableLevel1 ? displayControls : display.none
     )

//#endregion


//--------------------------------------------------------------------
//#region                         Debug
//--------------------------------------------------------------------

bgcolor(start1 ? color.new(openColorInput1, 80) : color(na))
//plot(changeIndex, "changeIndex", editable = false, display = display.status_line)
//plot(open1, "time1", editable = false, display = display.status_line)

//#endregion